### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by michael-rutherford** [Ilogeek/redmine_issue_dynamic_edit#16]
Just upgraded to newest version and found any time I make a dynamic change, the loading progress popup just goes and goes and goes and never goes away. I refresh and/or hit back and find that the change was made.

![dynamic_edit_error](https://user-images.githubusercontent.com/11825549/33783135-0102debe-dc21-11e7-9e48-3c750bf9a4c2.jpg)
![redmine_versions](https://user-images.githubusercontent.com/11825549/33783136-01304886-dc21-11e7-90d7-17b939f79c51.jpg)

Tested behavior in IE, Firefox and Chrome.

**Comment by Ilogeek** [comment]
Hello Michael,

- This problem only happens since your last update ? (the title and description edit ?) Was it working well before ?

- Do you think that a new plugin you installed may impact redmine_issue_dynamic_edit ?

- Could you please try again to update a field and check your JS console from your web browser ( [HowTo](https://webmasters.stackexchange.com/a/77337) ). You'll see something that will look like that : 

!(https://d26dzxoao6i3hh.cloudfront.net/items/2g2N460e3a1h2E1R3t3M/Image%202017-12-09%20at%207.40.45%20PM.png)

- Could you copy / paste it here and expand all possible object (error data for example) so we can look if there's a problem with the ajax call the plugin performs to update the issue.

I'm sure we will find a solution and make it works 👍

**Comment by TomyDMG** [comment]
Hi, have same problem.
Output from js console after change any field:

```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4
ajax @ jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4
issueDynamicUpdate @ issue_dynamic_edit.js:150
(anonymous) @ issue_dynamic_edit.js:266
dispatch @ jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:3
r.handle @ jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:3
ListPicker._handleMouseUp
jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4 Uncaught TypeError: Cannot read property 'hasChildNodes' of undefined
    at jsToolBar.draw (jstoolbar-textile.min.js:1)
    at initEditFieldListeners (issue_dynamic_edit.js:375)
    at Object.success (issue_dynamic_edit.js:210)
    at j (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:2)
    at x (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4)
    at b (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4)
    at Object.send (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4)
    at Function.ajax (jquery-1.11.1-ui-1.11.0-ujs-3.1.4.js:4)
    at issueDynamicUpdate (issue_dynamic_edit.js:150)
```

**Comment by TomyDMG** [comment]
And this message on page refresh:
```
Uncaught TypeError: Cannot read property 'hasChildNodes' of undefined
    at jsToolBar.draw (jstoolbar-textile.min.js:1)
    at initEditFieldListeners (issue_dynamic_edit.js:375)
    at issue_dynamic_edit.js:380
```

**Comment by Ilogeek** [comment]
Hello @TomyDMG 

Thank you for your help and your messages.
Thanks to them I was able to discover the problem and fixed it !

The problem occured when there were no description for the current issue. I added a condition to avoid the JS error and everything works fine now

If you find any problem with this update don't hesitate to post it here and we will find a solution

If you find the plugin helpful, please take a minute and rate it on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
