### ISSUE TITLE
Doesn't allow editing 2 times on the same page consiquently

### ISSUE THREAD

**Issue by larinam** [Ilogeek/redmine_issue_dynamic_edit#28]
Have a problem on the frontend with this plugin. 
After editing any field or different fields more than one time, I receive the following issue.
<img width="1416" alt="screenshot 2018-08-29 15 38 59" src="https://user-images.githubusercontent.com/233310/44792333-f0a27e00-aba3-11e8-93db-4f45e8ec390f.png">

**Comment by Ilogeek** [comment]
Hello @larinam 

Thank you for your feedback. Unfortunately I can't reproduce your issue right now. Could you please answer these questions below and we will find a way to fix your issue :

- Could you list all the plugins you use on your Redmine instance ? ( Could some of them have an interaction with the normal Redmine behaviour ? )
- It's strange that Chrome try to use custom Datepicker, do you have any plugin that modify your datetime field ? (that question is about the first JS error)
- Could you find in the source of your page the div element named : `required_field_array` It's something like : `<div style='display:none' id='required_field_array'>[ ... ]</div>` and paste here it's content ? (that question is about the second JS error)
- Do you try to update some fields that have some restrictions ? (e.g. break your workflow)

**Comment by Ilogeek** [comment]
Hello @larinam 

Thank you for your complete return that helped a lot.

It looks like this problem happens when you have a plugin that edit issue value automatically (Computed custom field plugin in this case). An other user has the same kind of problem here #26 with Checklists plugin. 

By editing automatically a field in your Redmine issue it creates a new state for your Redmine issue and when my plugin tries to update it, a conflict is raised. 

I will update my plugin to avoid this situation and I'll come back to you

**Comment by ddk85** [comment]
Same trouble with pencils :)

Also cann't change due date.

**Comment by TrumanRu** [comment]
The same problem.

**Comment by Ilogeek** [comment]
Hi,

(Thank you all for your last comments with great info helping the community resolves the issue. Don't hesitate to commit your PR if you find any solution)

It sounds like there are some conflicts with other plugins such as "A common libraries" ( Eg: #42 )
This may cause your issue here, do you also use this plugin ? 

I've updated the plugin and tried it with the last Redmine version vanilla (any plugin installed) and it works fine. 
* What happens when you deactivate "A common libraries" ? Do you still have this issue ? 

This plugin may alter default select elements or datepicker elements and give this kind of behavior. I'll check it by installing it

**Comment by dirmax** [comment]
Hi,

Use version 2.5.3 of a_common_libs. Don't activate option "~Включить ajax загрузку формы редактирования задачи" (missed english label :) in settings

**Comment by Ilogeek** [comment]
Hi @dirmax 

Well done, i've just tested your solution and it works like a charm !

On the "_A common libs_" settings page on your Redmine instance administration (`settings/plugin/a_common_libs`) **uncheck the last element** that appears in Other setting (which is not translated). It's a setting named `enable_ajax_edit_form` in the code, "_Включить ajax загрузку формы редактирования задачи_" as current label (it's not translated in the plugin) :
<br/>

![Uncheck the last element](https://i.ibb.co/44c3473/Capture-d-e-cran-2019-04-14-a-23-08-36.png "Uncheck the last element")
You can then apply your modification
