### ISSUE TITLE
temporarily switch off

### ISSUE THREAD

**Issue by Dork507** [Ilogeek/redmine_issue_dynamic_edit#30]
Hello,

is it possible to insert a switch, where users can switch off the dynamic edit.
Our users often use the copy/paste function. In this case dynamic edit is disturbing.

Thank you

**Comment by masgo** [comment]
I have the same problem regarding copy/paste. For me, it would solve the problem if editing would only be triggered if I click on the pencil icon. So, doubleclicking on text (in order to mark it) would simply do nothing.

**Comment by Ilogeek** [comment]
Hi,

Thank you for your feedback. I've just updated the plugin with this new feature that allow you to choose which action will trigger the edit box (click, or double-click) and which area needs to be clicked (full area or only the pencil). 

You've got all the info at https://github.com/Ilogeek/redmine_issue_dynamic_edit#--configuration-new-since-v-066 but for your example you just have to edit `assets/javascripts/issue_dynamic_edit_configuration_file.js` line 27 with `var _CONF_LISTENER_TARGET = "fa-pencil";` . This would do the trick !

If you find the plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍
