### ISSUE TITLE
Issue's style classes doesn't follow status nor priority

### ISSUE THREAD

**Issue by TrumanRu** [Ilogeek/redmine_issue_dynamic_edit#4]
I use custom styles to make accent on some priorities and statuses.

I change status or priority of an issue but classes of element `#content > div.issue` doesn't change.

**Comment by TrumanRu** [comment]
Some links.

1. Priority classes: http://www.redmine.org/projects/redmine/repository/revisions/10720
2. Changed issues css class from priority-{position} to priority-{id}: http://www.redmine.org/projects/redmine/repository/revisions/10079
3. Changed issues css class from status-{position} to status-{id}: http://www.redmine.org/projects/redmine/repository/revisions/10078
4. Add status, assigned_to and done_ratio classes to issue subtasks: http://www.redmine.org/projects/redmine/repository/revisions/15251

**Comment by Ilogeek** [comment]
Hello @TrumanRu 

Thank you for your feedback. The problem was that it wasn't a full text value that was displayed but directly the input or dropdown list with a specific style. That's why your custom style didn't applied to them. 

I edited the way to display edit fields in the **0.4.0 version** and added the ability to update css class to the issue depending on its status and priority. Don't hesitate to tell me if you find any problem with the solution
