### ISSUE TITLE
custom fileds with fields permissions support

### ISSUE THREAD

**Issue by xuebowen09** [Ilogeek/redmine_issue_dynamic_edit#45]
first of all, thank you so much for develop this useful plugin!
however, our work team force me to use fields permissions to behave our developers.
here is the screenshot of the problem.
![屏幕快照 2019-04-10 上午11 37 31](https://user-images.githubusercontent.com/24449154/55850326-78af2400-5b86-11e9-83cd-d58d05d77f61.png)
![屏幕快照 2019-04-10 上午11 44 57](https://user-images.githubusercontent.com/24449154/55850327-78af2400-5b86-11e9-9dbf-3dd434c6509a.png)
Is there any possibilities to solve this problems?
Thank you again for reading this issue!

**Comment by Ilogeek** [comment]
Hello @xuebowen09 

Thank you for your kind message !

If the custom field has the "read only" parameter sets you can't modify this field by clicking on the "edit" button that's why you can't modify it using the plugin too. There's no way to dynamically edit a field you can't modify because of some administration settings (it will be the same on the specific edit page of the issue for example).

If you change the "read-only" permission attribute does it resolve your problem ? I've also implemented a configuration file where you can exclude some fields ( try looking at issue #41 ) maybe this feature could help you ?
