### ISSUE TITLE
Editing should start only with edit button, not with click on field

### ISSUE THREAD

**Issue by markusneg** [Ilogeek/redmine_issue_dynamic_edit#78]
In my case editing starts when clicking anywhere in the field. However, editing should only start upon clicking the edit button (small pencil icon). Otherwise you cannot copy & paste stuff without opening a pop-up.

**Comment by Ilogeek** [comment]
**Hello** @markusneg 

Have you considered configuration options listed into the [README.md](https://github.com/Ilogeek/redmine_issue_dynamic_edit#--configuration-new-since-v-066) file ?

I'm sure [_CONF_LISTENER_TARGET](https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/master/assets/javascripts/issue_dynamic_edit_configuration_file.js#L42) is exactly what you need :
Update line 42 with `var _CONF_LISTENER_TARGET = "fa-pencil";` and restart your redmine instance

If you find the plugin helpful, take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit 👍

**Have a good day too**

**Comment by markusneg** [comment]
Oops, obviously I missed that configuration options. Thanks for the hint.
