### ISSUE TITLE
Control elements for editing not hidden in css print style

### ISSUE THREAD

**Issue by mrniemand** [Ilogeek/redmine_issue_dynamic_edit#84]
the control elements of the plugin are all visible when an issue is printed.

for testing i added the follow to application.css

@media print {
	.dynamicEdit, .dynamicEditIcon { display: none !important; }
}
But i don't have an idea where to extend the plugin. Above code in plugin css directory doesn't change something.

**Comment by Ilogeek** [comment]
Hi @mrniemand 

Issue was fixed with the last commit : https://github.com/Ilogeek/redmine_issue_dynamic_edit/commit/99de29a7a8f2eae406f776e7f5844bf58cd8eab2
CSS rule has been added directly into `view_issues_show_details_bottom`

Don't hesitate to reopen this issue if you have difficulties with the fix.

> If you find this plugin helpful, please take a minute to star it on Github and rate it 5 stars on http://www.redmine.org/plugins/redmine_issue_dynamic_edit thank you very much 👍
