### ISSUE TITLE
0.8.1 Page not found 

### ISSUE THREAD

**Issue by ashrafalzyoud** [Ilogeek/redmine_issue_dynamic_edit#92]
give page not found when i click in buttom refresh data in subtask
Page not found

**Comment by ashrafalzyoud** [comment]
@Ilogeek

**Comment by Ilogeek** [comment]
> @Ilogeek

Yes ?

**Comment by ashrafalzyoud** [comment]
There are problems in parent and subtasks there are button refresh 
It's give page not found

**Comment by openncomp** [comment]
I have the same problem after the update.
I don’t understand why they added this button, it looks terrible.

**Comment by Ilogeek** [comment]
@ashrafalzyoud @openncomp thank you very much for your help and kind words
Comments and code proposal were really helpful and motivational (+1 for the comment with only my nickname just because you're impatient) 👍

You can still hide the button by commenting this line : https://github.com/Ilogeek/redmine_issue_dynamic_edit/blob/cbd2e36a37d780383cace9c7541cd6a0a9507bc8/assets/javascripts/issue_dynamic_edit.js#L110

Last commit should resolve the issue (the refreshData button must only appears for current issue and not subtask, there was also an issue clicking on the button)
